question_data = [
{"question":"In 2019, Minecraft outsold Tetris to become the world's best-selling video game.","correct_answer":"True"},
{"question":"Pac-Man was invented by the designer Toru Iwatani while he was eating pizza.","correct_answer":"True"},
{"question":"Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series history.","correct_answer":"True"},
{"question":"Faust is a playable character in Guilty Gear Xrd Revelator.","correct_answer":"True"},
{"question":"There are 2 player roles in Trouble in Terrorist Town.","correct_answer":"False"},
{"question":"The main antagonist in the videogame Saints Row IV is an entity known as The Mastermind.","correct_answer":"False"},
{"question":"In the game Destiny, the three subclasses of the Hunter are Bladedancer, Nightstalker, and Sunsinger.","correct_answer":"False"},
{"question":"The ultimate phrase used by Pharah from Overwatch is: Justice rains from above!","correct_answer":"True"},
{"question":"In Sonic Adventure, you are able to transform into Super Sonic at will after completing the main story.","correct_answer":"False"},
{"question":"Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the game's plot.","correct_answer":"True"},
{"question":"In the game Subnautica, a Spadefish will attack you.","correct_answer":"False"},
{"question":"The shotgun appears in every numbered Resident Evil game.","correct_answer":"True"},
{"question":"In the Monster Hunter Series, G-Rank is the highest possible prestige a Hunter can receive.","correct_answer":"True"},
{"question":"The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, went bankrupt on March 1st, 2010.","correct_answer":"True"},
{"question":"In Kingdom Hearts the Paopu fruit is said to intertwine the destinies for two people forever.","correct_answer":"True"},
{"question":"The end credits sequence in Grand Theft Auto 5 is over half an hour long.","correct_answer":"True"},
{"question":"Doki Doki Literature Club was developed in Japan.","correct_answer":"False"},
{"question":"Rollercoaster Tycoon 1 and 2 were developed by Chris Sawyer.","correct_answer":"True"},
{"question":"In Terraria, you can craft the Cell Phone pre-hardmode.","correct_answer":"True"},
{"question":"Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.","correct_answer":"False"},
{"question":"In Pokemon, Arbok evolves into Seviper.","correct_answer":"False"},
{"question":"Each piece in Tetris is called a tetris.","correct_answer":"False"},
{"question":"Watch Dogs 2 is a prequel.","correct_answer":"False"},
{"question":"Metal Gear Solid 3: Snake Eater was released in 2004.","correct_answer":"True"},
{"question":"In Resident Evil 4, the Chicago Typewriter has infinite ammo.","correct_answer":"True"},
{"question":"The song Megalovania by Toby Fox made its third appearance in the 2015 RPG Undertale.","correct_answer":"True"},
{"question":"Half-Life 2 runs on the Source Engine.","correct_answer":"True"},
{"question":"Big the Cat is a playable character in Sonic Generations.","correct_answer":"False"},
{"question":"The main playable character of the 2015 RPG Undertale is a monster.","correct_answer":"False"},
{"question":"In Space Station 13, the station has a clown aboard it.","correct_answer":"True"},
{"question":"In the Super Mario series, the character Pauline is a Princess like Princess Peach.","correct_answer":"False"},
{"question":"In Tony Hawk's Underground, the main character's friend turned rival is named Jeff Sampson.","correct_answer":"False"},
{"question":"In Team Fortress 2, being disguised as a scout or medic results in a speed boost.","correct_answer":"False"},
{"question":"Super Mario Bros. was the first video game ever created.","correct_answer":"False"},
{"question":"In the S.T.A.L.K.E.R. series, the Freedom faction wishes to destroy the supernatural area known as the Zone.","correct_answer":"False"},
{"question":"In RuneScape, one must complete the Dragon Slayer quest before equipping Rune Platelegs.","correct_answer":"False"},
{"question":"The main character in the Half-Life franchise is named Morgan Freeman.","correct_answer":"False"},
{"question":"In Pokemon Sun and Moon, a male Salandit can evolve to a Salazzle.","correct_answer":"False"},
{"question":"The ghosts in Pac-Man and Ms. Pac-Man have completely different behavior.","correct_answer":"True"},
{"question":"The Konami Code is known as Up, Up, Down, Down, Left, Right, Right, Left, B, A, Start.","correct_answer":"False"},
{"question":"Gordon Freeman, the protagonist of Half-Life, is said to have once had a ponytail.","correct_answer":"True"},
{"question":"Valve's Portal and Half-Life franchises exist within the same in-game universe.","correct_answer":"True"},
{"question":"In the Half-Life series, H.E.V stands for Hazardous Evasiveness Vest.","correct_answer":"False"},
{"question":"Undertale is an RPG created by Toby Fox and released in 2015.","correct_answer":"True"},
{"question":"In Undertale, the main character of the game is Sans.","correct_answer":"False"},
{"question":"Several characters in Super Mario 64 blink their eyes, including Mario himself.","correct_answer":"True"},
{"question":"Minecraft can be played with a virtual reality headset.","correct_answer":"True"},
{"question":"In the Monster Hunter Series, it is possible to capture Elder Dragons.","correct_answer":"False"},
{"question":"In Heroes of the Storm, the Cursed Hollow map gimmick requires players to kill the undead to curse the enemy team.","correct_answer":"False"},
{"question":"The game Pocket Morty has a Morty called Pocket Mortys Morty?","correct_answer":"True"}
]