#- - - - USO DEL MAP - - - -
#IL MAP e' UNA FUNZIONE DI PYTHON CHE FUNZIONA SU GLI ELEMENTI ITERABILI
#PRENDE UNA FUNZIONE E LA APPLICA AUTOMATICAMENTE A GLI ELEMENTI DI UN ITERABILE
#MODO PIU' COMPATTO PER FARE AZIONI DI QUESTO TIPO


#ESEMPIO:
#LA FUNZIONE str.upper VIENE APPLICATA SUGLI ELEMENTI DELLA LISTA MESSA COME PARAMETRO
#AVENDO RACCHIUSO IL TUTTO ALL'INTERNO DI UNA LISTA, QUESTI ELEMENTI VENGONO CREATI NELLA LISTA
#NOTA: LA FUNZIONE NON HA LE PARENTESI TONDE ALLA FINE, PERCHÈ' ALTRIMENTI LE PARENTESI FAREBBERO PARTIRE LA FUNZIONE SUBITO
nomi = list(map(str.upper, ["alice", "bob", "carlo", "gino"]))

print(nomi)

#ALTRO MODO PER FARE LA STESSA COSA

nomi2 = []
for i in ["alice", "bob", "carlo", "gino"]:
    nomi2.append(i.upper())

print(nomi2)